require_all 'app/models'

Location.destroy_all
loc_queens = Location.create(name: "Queens")
loc_brooklyn = Location.create(name: "Brooklyn")
loc_bronx = Location.create(name: "The Bronx")
loc_manhattan = Location.create(name: "Manhattan")
loc_staten = Location.create(name: "Staten Island")
loc_nj = Location.create(name: "New Jersey")

Structure.destroy_all
str_throgsneck = Structure.create(name: "Throgs Neck Bridge", toll_amount: 5.76)
str_whitestone = Structure.create(name: "Whitestone Bridge", toll_amount: 5.76)
str_triboro = Structure.create(name: "Triboro Bridge", toll_amount: 5.76)
str_queensboro = Structure.create(name: "Queensboro Bridge", toll_amount: 0)
str_queensmidtown = Structure.create(name: "Queens-Midtown Tunnel", toll_amount: 5.76)
str_williamsburg = Structure.create(name: "Williamsburg Bridge", toll_amount: 0)
str_manhattan = Structure.create(name: "Manhattan Bridge", toll_amount: 0)
str_brooklyn = Structure.create(name: "Brooklyn Bridge", toll_amount: 0)
str_battery = Structure.create(name: "Brooklyn-Battery Tunnel", toll_amount: 5.76)
str_verrazano = Structure.create(name: "Verrazano-Narrows Bridge", toll_amount: 11.52)
str_goethals = Structure.create(name: "Goethals Bridge", toll_amount: 10.5)
str_holland = Structure.create(name: "Holland Tunnel", toll_amount: 10.5)
str_lincoln = Structure.create(name: "Lincoln Tunnel", toll_amount: 10.5)
str_georgewashington = Structure.create(name: "George Washington Bridge", toll_amount: 10.5)
str_henryhudson = Structure.create(name: "Henry Hudson Bridge", toll_amount: 2.64)


Crossing.destroy_all
Crossing.create(name: "GWBR NJS-MAN", has_toll: true, start_location_id: loc_nj.id, end_location_id: loc_manhattan.id, structure_id: str_georgewashington.id)
Crossing.create(name: "GWBR MAN-NJS", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_nj.id, structure_id: str_georgewashington.id)
Crossing.create(name: "TRIB BRX-MAN", has_toll: true, start_location_id: loc_bronx.id, end_location_id: loc_manhattan.id, structure_id: str_triboro.id)
Crossing.create(name: "TRIB MAN-BRX", has_toll: true, start_location_id: loc_manhattan.id, end_location_id: loc_bronx.id, structure_id: str_triboro.id)
Crossing.create(name: "TRIB BRX-QNS", has_toll: true, start_location_id: loc_bronx.id, end_location_id: loc_queens.id, structure_id: str_triboro.id)
Crossing.create(name: "TRIB QNS-BRX", has_toll: true, start_location_id: loc_queens.id, end_location_id: loc_bronx.id, structure_id: str_triboro.id)
Crossing.create(name: "TRIB QNS-MAN", has_toll: true, start_location_id: loc_queens.id, end_location_id: loc_manhattan.id, structure_id: str_triboro.id)
Crossing.create(name: "TRIB MAN-QNS", has_toll: true, start_location_id: loc_manhattan.id, end_location_id: loc_queens.id, structure_id: str_triboro.id)
Crossing.create(name: "HEHB BRX-MAN", has_toll: true, start_location_id: loc_bronx.id, end_location_id: loc_manhattan.id, structure_id: str_henryhudson.id)
Crossing.create(name: "HEHB MAN-BRX", has_toll: true, start_location_id: loc_manhattan.id, end_location_id: loc_bronx.id, structure_id: str_henryhudson.id)
Crossing.create(name: "QNSB MAN-QNS", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_queens.id, structure_id: str_queensboro.id)
Crossing.create(name: "QNSB QNS-MAN", has_toll: false, start_location_id: loc_queens.id, end_location_id: loc_manhattan.id, structure_id: str_queensboro.id)
Crossing.create(name: "QMDT MAN-QNS", has_toll: true, start_location_id: loc_manhattan.id, end_location_id: loc_queens.id, structure_id: str_queensmidtown.id)
Crossing.create(name: "QMDT QNS-MAN", has_toll: true, start_location_id: loc_queens.id, end_location_id: loc_manhattan.id, structure_id: str_queensmidtown.id)
Crossing.create(name: "WILB MAN-BKN", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_brooklyn.id, structure_id: str_williamsburg.id)
Crossing.create(name: "WILB BKN-MAN", has_toll: false, start_location_id: loc_brooklyn.id, end_location_id: loc_manhattan.id, structure_id: str_williamsburg.id)
Crossing.create(name: "MANB MAN-BKN", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_brooklyn.id, structure_id: str_manhattan.id)
Crossing.create(name: "MANB BKN-MAN", has_toll: false, start_location_id: loc_brooklyn.id, end_location_id: loc_manhattan.id, structure_id: str_manhattan.id)
Crossing.create(name: "BKNB MAN-BKN", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_brooklyn.id, structure_id: str_brooklyn.id)
Crossing.create(name: "BKNB BKN-MAN", has_toll: false, start_location_id: loc_brooklyn.id, end_location_id: loc_manhattan.id, structure_id: str_brooklyn.id)
Crossing.create(name: "BATT MAN-BKN", has_toll: true, start_location_id: loc_manhattan.id, end_location_id: loc_brooklyn.id, structure_id: str_battery.id)
Crossing.create(name: "BATT BKN-MAN", has_toll: true, start_location_id: loc_brooklyn.id, end_location_id: loc_manhattan.id, structure_id: str_battery.id)
Crossing.create(name: "LINT MAN-NJS", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_nj.id, structure_id: str_lincoln.id)
Crossing.create(name: "LINT NJS-MAN", has_toll: true, start_location_id: loc_nj.id, end_location_id: loc_manhattan.id, structure_id: str_lincoln.id)
Crossing.create(name: "HOLT MAN-NJS", has_toll: false, start_location_id: loc_manhattan.id, end_location_id: loc_nj.id, structure_id: str_holland.id)
Crossing.create(name: "HOLT NJS-MAN", has_toll: true, start_location_id: loc_nj.id, end_location_id: loc_manhattan.id, structure_id: str_holland.id)
Crossing.create(name: "GOEB STI-NJS", has_toll: false, start_location_id: loc_staten.id, end_location_id: loc_nj.id, structure_id: str_goethals.id)
Crossing.create(name: "GOEB NJS-STI", has_toll: true, start_location_id: loc_nj.id, end_location_id: loc_staten.id, structure_id: str_goethals.id)
Crossing.create(name: "VERB BKN-STI", has_toll: true, start_location_id: loc_brooklyn.id, end_location_id: loc_staten.id, structure_id: str_verrazano.id)
Crossing.create(name: "VERB STI-BKN", has_toll: false, start_location_id: loc_staten.id, end_location_id: loc_brooklyn.id, structure_id: str_verrazano.id)
Crossing.create(name: "WHTB QNS-BRX", has_toll: true, start_location_id: loc_queens, end_location_id: loc_bronx.id, structure_id: str_whitestone.id)
Crossing.create(name: "WHTB BRX-QNS", has_toll: true, start_location_id: loc_bronx.id, end_location_id: loc_queens.id, structure_id: str_whitestone.id)
Crossing.create(name: "THRB QNS-BRX", has_toll: true, start_location_id: loc_queens, end_location_id: loc_bronx.id, structure_id: str_throgsneck.id)
Crossing.create(name: "THRB BRX-QNS", has_toll: true, start_location_id: loc_bronx.id, end_location_id: loc_queens.id, structure_id: str_throgsneck.id)
